language: node_js
node_js: node
dist: xenial

script:
    - npm i mocha eslint typescript-eslint @typescript-eslint/eslint-plugin @typescript-eslint/parser
    - npm run test

notifications:
  email: false
