language: node_js
node_js: node
dist: xenial

script:
    - npm i mocha eslint typescript-eslint @typescript-eslint/eslint-plugin @typescript-eslint/parser
    - mocha out/**/*.spec.js -s 0
    - eslint src/**/*.ts

notifications:
  email: false
