language: node_js
node_js: node
jobs:
  include:
    - dist: xenial
      script: npm install mocha && npm install eslint --save-dev && npm install typescript-eslint --save-dev && npm install @typescript-eslint/eslint-plugin --save-dev && npm install @typescript-eslint/parser --save-dev && npm install mocha out/**/*.spec.js -s 0 && eslint src/**/*.ts

notifications:
  email: false
