language: node_js
dist: xenial
sudo: required

# Use this to prepare the system to install prerequisites or dependencies.
# e.g. sudo apt-get update.
# Failures in this section will result in build status 'errored'.
before_install:
    - sudo rm -rf ~/.nvm
    - curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash -
    - sudo apt-get install -y nodejs
    - if [[ `node -v` != v10* ]]; then nvm install stable; fi
    - nvm install-latest-npm
    - nvm install 15.14.0
    - nvm use 15.14.0

# Use this to prepare the system to install prerequisites or dependencies.
# e.g. sudo apt-get update.
# Failures in this section will result in build status 'errored'.
before_install:
    - sudo rm -rf ~/.nvm
    - curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash -
    - sudo apt-get install -y nodejs
    - if [[ `node -v` != v15* ]]; then nvm install stable; fi
    - nvm install-latest-npm
    - nvm install 15.14.0
    - nvm use 15.14.0

# Use this to prepare your build for testing.
# e.g. copy database configurations, environment variables, etc.
# Failures in this section will result in build status 'errored'.
before_script:
    - npm i -g mocha@9.1.1 eslint@8.15.0 typescript-eslint @typescript-eslint/eslint-plugin @typescript-eslint/parser

script:
    - npm run build
    - npm run test

notifications:
  email: true
